from typing import Protocol

class BillProtocol(Protocol):
    def persist(self,bill):
        ...

    def getById(self,id: int):
        ...

    def listBillFromAndTo(self,f:int,t:int):
        ...

    def listDraftBill(self):
        ...

    def listOutstandingBill(self):
        ...

    def listCompletedBill(self):
        ...

    def listCancelledBill(self):
        ...

    def update(self,id,bill):
        ...

    def persistBillItem(self,billItem):
        ...

    def deleteBillItem(self,id):
        ...

    def persistDeposit(self,deposit):
        ...

    def updateDeposit(self,id,deposit):
        ...

    def getDepositById(self,id: int):
        ...

    def updateBillItem(self,id:int,billItem):
        ...

    def getBillItemById(self,id: int):
        ...

    def listDepositFromAndTo(self,f:int,t:int):
        ...

    def listActiveDeposit(self):
        ...

    def listCancelledDeposit(self):
        ...

    def listActiveDepositByPatientId(self,id):
        ...

    def listUsedDeposit(self):
        ...

    def persistDepositUsed(self,depositUsed):
        ...

    def persistPayment(self,payment):
        ...

    def updatePayment(self,id,payment):
        ...