from typing import Protocol

class SalesServiceItemProtocol(Protocol):
    def persist(self,salesServiceItem):
        ...
    
    def persistUom(self,uom):
        ...

    def persistCategory(self,category):
        ...

    def update(self,id,salesServiceItem):
        ...

    def updateUom(self,id,uom):
        ...

    def updateCategory(self,id,uom):
        ...

    def list(self):
        ...

    def listUom(self):
        ...

    def listCategory(self):
        ...

    def delete(self,id):
        ...

    def deleteUom(self,id):
        ...

    def deleteCategory(self,id):
        ...

    def getById(self,id: int):
        ...
    
    def getUomById(self,id: int):
        ...

    def getCategoryById(self,id: int):
        ...