"""17_6_2022_make_sure_invtory_item_sales_service_item_is_one_to_one

Revision ID: 0bb5e057ab99
Revises: 497c7245f498
Create Date: 2022-06-17 12:26:22.951925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb5e057ab99'
down_revision = '497c7245f498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventoryitem_sales_service_item_id', table_name='inventoryitem')
    op.create_index(op.f('ix_inventoryitem_sales_service_item_id'), 'inventoryitem', ['sales_service_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventoryitem_sales_service_item_id'), table_name='inventoryitem')
    op.create_index('ix_inventoryitem_sales_service_item_id', 'inventoryitem', ['sales_service_item_id'], unique=False)
    # ### end Alembic commands ###
