"""removedPatientAge

Revision ID: 11346a891d36
Revises: a917f68fae0a
Create Date: 2021-12-15 16:29:55.402445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11346a891d36'
down_revision = 'a917f68fae0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'patient_age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_age', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
