"""9_7_2022_removed_pharmacy_item

Revision ID: 20e9920e029a
Revises: 28acfa110482
Create Date: 2022-07-09 21:46:08.463619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e9920e029a'
down_revision = '28acfa110482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pharmacyitem_category_id', table_name='pharmacyitem')
    op.drop_index('ix_pharmacyitem_created_user_id', table_name='pharmacyitem')
    op.drop_index('ix_pharmacyitem_id', table_name='pharmacyitem')
    op.drop_index('ix_pharmacyitem_updated_user_id', table_name='pharmacyitem')
    op.alter_column('inventoryitem', 'sales_service_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('inventoryitem_pharmacy_item_id_fkey', 'inventoryitem', type_='foreignkey')
    op.drop_column('inventoryitem', 'pharmacy_item_id')
    op.drop_table('pharmacyitem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacyitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('form', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('po_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('converstion_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pharmacyitem_pkey')
    )
    op.create_index('ix_pharmacyitem_updated_user_id', 'pharmacyitem', ['updated_user_id'], unique=False)
    op.create_index('ix_pharmacyitem_id', 'pharmacyitem', ['id'], unique=False)
    op.create_index('ix_pharmacyitem_created_user_id', 'pharmacyitem', ['created_user_id'], unique=False)
    op.create_index('ix_pharmacyitem_category_id', 'pharmacyitem', ['category_id'], unique=False)
    op.add_column('inventoryitem', sa.Column('pharmacy_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inventoryitem_pharmacy_item_id_fkey', 'inventoryitem', 'pharmacyitem', ['pharmacy_item_id'], ['id'])
    op.alter_column('inventoryitem', 'sales_service_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
