"""18_6_2022_removed_unique_of_ssi_in_invitem

Revision ID: 664d6e199417
Revises: 0bb5e057ab99
Create Date: 2022-06-18 18:57:36.937287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664d6e199417'
down_revision = '0bb5e057ab99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventoryitem_sales_service_item_id', table_name='inventoryitem')
    op.create_index(op.f('ix_inventoryitem_sales_service_item_id'), 'inventoryitem', ['sales_service_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventoryitem_sales_service_item_id'), table_name='inventoryitem')
    op.create_index('ix_inventoryitem_sales_service_item_id', 'inventoryitem', ['sales_service_item_id'], unique=False)
    # ### end Alembic commands ###
