"""billColumnNameChange

Revision ID: 89992a39c9c4
Revises: c26ee998a214
Create Date: 2021-12-17 09:44:41.381378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89992a39c9c4'
down_revision = 'c26ee998a214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_address', sa.String(), nullable=False))
    op.drop_column('bill', 'patient_addres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_addres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bill', 'patient_address')
    # ### end Alembic commands ###
