"""init

Revision ID: 8d748857e6dd
Revises: 5f4c39d8973b
Create Date: 2021-11-01 08:23:59.803856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d748857e6dd'
down_revision = '5f4c39d8973b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'patient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
