"""init

Revision ID: a0d21a780cff
Revises: 8d748857e6dd
Create Date: 2021-11-01 10:28:20.359535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d21a780cff'
down_revision = '8d748857e6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basemodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basemodel_id'), 'basemodel', ['id'], unique=False)
    op.add_column('patient', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('patient', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patient', sa.Column('created_user_id', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('updated_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'user', ['updated_user_id'], ['id'])
    op.create_foreign_key(None, 'patient', 'user', ['created_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'updated_user_id')
    op.drop_column('patient', 'created_user_id')
    op.drop_column('patient', 'updated_time')
    op.drop_column('patient', 'created_time')
    op.drop_index(op.f('ix_basemodel_id'), table_name='basemodel')
    op.drop_table('basemodel')
    # ### end Alembic commands ###
