"""27_5_2022_added_is_active_salesServiceItem

Revision ID: a3b374b377db
Revises: cf0120b94aa4
Create Date: 2022-05-27 11:39:30.533962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b374b377db'
down_revision = 'cf0120b94aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salesserviceitem', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesserviceitem', 'is_active')
    # ### end Alembic commands ###
