"""billAndPayment

Revision ID: a917f68fae0a
Revises: d07f766a549f
Create Date: 2021-12-15 14:56:07.065246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a917f68fae0a'
down_revision = 'd07f766a549f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    printed_or_drafted_enum = postgresql.ENUM('printed', 'drafted', name='printed_or_drafted_enum')
    printed_or_drafted_enum.create(op.get_bind())
    op.add_column('bill', sa.Column('printed_or_drafted', sa.Enum('printed', 'drafted', name='printed_or_drafted_enum'), nullable=True))
    op.add_column('billitem', sa.Column('bill_id', sa.Integer(), nullable=True))
    op.alter_column('billitem', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('billitem_patient_id_fkey', 'billitem', type_='foreignkey')
    op.create_foreign_key(None, 'billitem', 'bill', ['bill_id'], ['id'])
    op.drop_column('billitem', 'patient_id')
    op.add_column('payment', sa.Column('unpaid_amount', sa.Integer(), nullable=False))
    op.drop_column('payment', 'total_outstanding_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('total_outstanding_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payment', 'unpaid_amount')
    op.add_column('billitem', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billitem', type_='foreignkey')
    op.create_foreign_key('billitem_patient_id_fkey', 'billitem', 'patient', ['patient_id'], ['id'])
    op.alter_column('billitem', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('billitem', 'bill_id')
    op.drop_column('bill', 'printed_or_drafted')
    # ### end Alembic commands ###
