"""added_cancel_status

Revision ID: ac2289871ec5
Revises: ad6bfe025634
Create Date: 2022-01-30 22:40:23.495954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2289871ec5'
down_revision = 'ad6bfe025634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('is_cancelled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('deposit', sa.Column('is_cancelled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'is_cancelled')
    op.drop_column('bill', 'is_cancelled')
    # ### end Alembic commands ###
