"""updatedDepositUsed

Revision ID: ad6bfe025634
Revises: e5b7c3c703b4
Create Date: 2021-12-23 11:45:30.219251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6bfe025634'
down_revision = 'e5b7c3c703b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depositused', sa.Column('deposit_amount', sa.Integer(), nullable=False))
    op.drop_column('depositused', 'collected_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depositused', sa.Column('collected_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('depositused', 'deposit_amount')
    # ### end Alembic commands ###
