"""billColumnChange

Revision ID: c26ee998a214
Revises: d94773382781
Create Date: 2021-12-17 09:40:32.515889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26ee998a214'
down_revision = 'd94773382781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_addres', sa.String(), nullable=False))
    op.drop_column('bill', 'patient_age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bill', 'patient_addres')
    # ### end Alembic commands ###
