"""deposit

Revision ID: c72a71910aba
Revises: 89992a39c9c4
Create Date: 2021-12-22 19:17:59.996060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72a71910aba'
down_revision = '89992a39c9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('remark', sa.String(), nullable=True))
    op.add_column('depositused', sa.Column('unpaid_amount', sa.Integer(), nullable=False))
    op.add_column('depositused', sa.Column('collected_amount', sa.Integer(), nullable=False))
    op.drop_column('depositused', 'outstanding_amount_after')
    op.drop_column('depositused', 'bill_id')
    op.drop_column('depositused', 'outstanding_amount_before')
    op.add_column('payment', sa.Column('is_outstanding', sa.Boolean(), nullable=True))
    op.drop_constraint('payment_patient_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'patient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_patient_id_fkey', 'payment', 'patient', ['patient_id'], ['id'])
    op.drop_column('payment', 'is_outstanding')
    op.add_column('depositused', sa.Column('outstanding_amount_before', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('depositused', sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('depositused', sa.Column('outstanding_amount_after', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('depositused', 'collected_amount')
    op.drop_column('depositused', 'unpaid_amount')
    op.drop_column('deposit', 'remark')
    # ### end Alembic commands ###
