"""Update_Patient_Date_of_Birth_Nullable

Revision ID: cf0120b94aa4
Revises: ac2289871ec5
Create Date: 2022-04-16 18:01:57.403825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0120b94aa4'
down_revision = 'ac2289871ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
