"""init

Revision ID: d07f766a549f
Revises: f6e103bcab51
Create Date: 2021-11-28 11:14:16.044793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07f766a549f'
down_revision = 'f6e103bcab51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
