"""7_9_2022_added_payment_type

Revision ID: d37c5bb9b62a
Revises: 20e9920e029a
Create Date: 2022-09-07 00:03:41.458625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37c5bb9b62a'
down_revision = '20e9920e029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_type_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_type_name')
    # ### end Alembic commands ###
