"""addedPatientAge

Revision ID: d94773382781
Revises: 11346a891d36
Create Date: 2021-12-15 16:30:20.567952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94773382781'
down_revision = '11346a891d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('patient_age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'patient_age')
    # ### end Alembic commands ###
