"""dailyClosing

Revision ID: e5b7c3c703b4
Revises: c72a71910aba
Create Date: 2021-12-23 11:15:23.561728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b7c3c703b4'
down_revision = 'c72a71910aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyclosing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_balance', sa.Integer(), nullable=False),
    sa.Column('deposit_total', sa.Integer(), nullable=False),
    sa.Column('bill_total', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.Column('actual_amount', sa.Integer(), nullable=False),
    sa.Column('adjusted_amount', sa.Integer(), nullable=False),
    sa.Column('adjusted_reason', sa.String(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyclosing_id'), 'dailyclosing', ['id'], unique=False)
    op.create_table('closingbilldetail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_closing_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['daily_closing_id'], ['dailyclosing.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closingbilldetail_id'), 'closingbilldetail', ['id'], unique=False)
    op.create_table('closingdepositdetail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_closing_id', sa.Integer(), nullable=True),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['daily_closing_id'], ['dailyclosing.id'], ),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposit.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closingdepositdetail_id'), 'closingdepositdetail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_closingdepositdetail_id'), table_name='closingdepositdetail')
    op.drop_table('closingdepositdetail')
    op.drop_index(op.f('ix_closingbilldetail_id'), table_name='closingbilldetail')
    op.drop_table('closingbilldetail')
    op.drop_index(op.f('ix_dailyclosing_id'), table_name='dailyclosing')
    op.drop_table('dailyclosing')
    # ### end Alembic commands ###
