"""init

Revision ID: f6e103bcab51
Revises: 157a9fc5344b
Create Date: 2021-11-28 11:13:26.547908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e103bcab51'
down_revision = '157a9fc5344b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
