"""removed blood type field

Revision ID: ff006d2af157
Revises: 6a45b1934522
Create Date: 2021-11-06 21:43:26.184893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff006d2af157'
down_revision = '6a45b1934522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'blood_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('blood_group', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
