"""7_9_2022_added_payment_type

Revision ID: ff9868bc0e9c
Revises: 20e9920e029a
Create Date: 2022-09-07 00:04:19.533995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9868bc0e9c'
down_revision = '20e9920e029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenttype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenttype_created_user_id'), 'paymenttype', ['created_user_id'], unique=False)
    op.create_index(op.f('ix_paymenttype_id'), 'paymenttype', ['id'], unique=False)
    op.create_index(op.f('ix_paymenttype_updated_user_id'), 'paymenttype', ['updated_user_id'], unique=False)
    op.add_column('payment', sa.Column('payment_type_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_type_name')
    op.drop_index(op.f('ix_paymenttype_updated_user_id'), table_name='paymenttype')
    op.drop_index(op.f('ix_paymenttype_id'), table_name='paymenttype')
    op.drop_index(op.f('ix_paymenttype_created_user_id'), table_name='paymenttype')
    op.drop_table('paymenttype')
    # ### end Alembic commands ###
