# This is the .github/workflows/main.yml

name: Deploy # Name of the workflow

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "hidtcop-api"
          heroku_email: "aungkokothet@thamardaw.com"
          healthcheck: "https://hidtcop-api.herokuapp.com/api/healthcheck"
          delay: 60 # for executing healthcheck 60s after action has started
          rollbackonhealthcheckfailed: true
      - name: Run migration
        run: heroku run alembic upgrade head -a hidtcop-api # run migration

