# This is the .github/workflows/main.yml

name: Prod deploy, build & push to docker hub # Name of the workflow

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main

jobs:
  deploy_and_push:
    name: Deploy to heroku and build and push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "hidtcop-api"
          heroku_email: "aungkokothet@thamardaw.com"
      - name: Run migration
        run: heroku run alembic upgrade head -a hidtcop-api # run migration

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: jasoniv/hidtcophospitalapi:latest
